name: Run Tests

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: python -m pip install --upgrade pip

    - name: Run Unit Tests
      run: |
        python -m unittest discover -s tests -p "unit_test.py"

    - name: Run Integration Tests
      run: |
        python -m unittest discover -s tests -p "integration_test.py"

